$('.footLi1').click(function(){
    location.assign('dingdan.html')
})
$('.footLi3').click(function(){
    location.assign('zhangdan.html')
})
$('.pic').click(function(){
    location.assign('tianjianyaopin.html')
})